[package]
description = "Recursive-length prefix encoding, decoding, and compression"
repository = "https://github.com/CodeChain-io/rlp"
license = "MIT/Apache-2.0"
name = "rlp"
version = "0.5.0"
authors = ["CodeChain Team <hi@codechain.io>", "Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
rustc-hex = "1.0"
ethereum-types = "0.3"

[dev-dependencies]
hex-literal = "0.2.1"
